services:

    #
    # Service
    #
    elcodi.manager.media_image:
        class: Elcodi\Component\Media\Services\ImageManager
        arguments:
            - @elcodi.factory.image
            - @elcodi.manager.media_file
            - @elcodi.media_resize_engine

    elcodi.manager.media_file:
        class: Elcodi\Component\Media\Services\FileManager
        arguments:
            - @elcodi.media_filesystem
            - @elcodi.transformer.media_file_identifier

    elcodi.uploader.image:
        class: Elcodi\Component\Media\Services\ImageUploader
        arguments:
            - @elcodi.object_manager.image
            - @elcodi.manager.media_file
            - @elcodi.manager.media_image
            - @elcodi.event_dispatcher.media

    #
    # Resize
    #
    elcodi.media_resize.imagemagick:
        class: Elcodi\Component\Media\Adapter\Resizer\ImageMagickResizeAdapter
        arguments:
            - %elcodi.image_resize_converter_bin_path%
