services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.media_image:
        class: Elcodi\Component\Media\Twig\ImageExtension
        arguments:
            - @router
            - elcodi.route.image_resize
            - elcodi.route.image_resize_seo
            - elcodi.route.image_view
            - elcodi.route.image_view_seo
            - %elcodi.image_generated_route_host%
        tags:
            - { name: twig.extension }
