services:

    #
    # Services
    #
    elcodi.location_provider.service:
        class: Elcodi\Component\Geo\Services\LocationServiceProvider
        arguments:
            - @elcodi.repository.location
            - @elcodi.transformer.location_to_location_data

    elcodi.location_provider.api:
        class: Elcodi\Component\Geo\Services\LocationApiProvider
        arguments:
            - @elcodi.factory.location_data
            - @router
            - @elcodi.location_api_urls
            - %elcodi.location_api_host%

    elcodi.location_api_urls:
        class: Elcodi\Component\Geo\ValueObject\ApiUrls
        arguments:
            - elcodi.route.location_api_root_locations
            - elcodi.route.location_api_children
            - elcodi.route.location_api_parents
            - elcodi.route.location_api_location
            - elcodi.route.location_api_hierarchy
            - elcodi.route.location_api_in

    elcodi.location_builder:
        class: Elcodi\Component\Geo\Services\LocationBuilder
        arguments:
            - @elcodi.factory.location

    elcodi.manager.address:
        class: Elcodi\Component\Geo\Services\AddressManager
        arguments:
            - @elcodi.director.address
            - @elcodi.object_manager.address
            - @elcodi.event_dispatcher.address
